/**
 * UserManagementPage — unified "Gestion utilisateur" page at `/account`
 * (specs/admin-account-management.md §6.1).
 *
 * Three sections (in order on screen):
 *   - "Mes informations" — every authenticated user edits their own identity fields
 *     (firstName, lastName, companyName, notes). Email is locked. Roles are NOT exposed — the
 *     server's PUT /api/users/me ignores any roles key in the payload (self-privilege guard).
 *   - "Mon mot de passe" — visible to every authenticated user (admin, accountant, any future role).
 *     Wraps ChangePasswordForm. On a forced first-login change, the server destroys the session and
 *     the page redirects to /login?reason=password-changed (same flow as the old /settings/password).
 *   - "Gestion des comptes" — admin-only (gated client-side via userHasRole + server-side via
 *     enforceRoleAccess). Lists every user, supports create / edit / reset password / soft+hard
 *     delete; per-row icon actions, table on md+, stacked cards on xs. Self-protection mirrors the
 *     server: the current admin cannot reset their own password from here, cannot remove their own
 *     admin role, and cannot delete themselves.
 *
 * The temporary password generated by create/reset is never returned by the API — the server emails
 * it directly. The UI surfaces success/failure as snackbars.
 */
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Box, Card, CardContent, Stack, Typography, Table, TableHead, TableRow, TableCell, TableBody,
  IconButton, Tooltip, Button, Alert, CircularProgress, useMediaQuery, Chip,
} from '@mui/material';
import { useTheme } from '@mui/material/styles';
import { useNavigate } from 'react-router-dom';
import EditIcon from '@mui/icons-material/Edit';
import VpnKeyIcon from '@mui/icons-material/VpnKey';
import ToggleOnIcon from '@mui/icons-material/ToggleOn';
import ToggleOffIcon from '@mui/icons-material/ToggleOff';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import PersonAddAlt1Icon from '@mui/icons-material/PersonAddAlt1';
import api from '../api';
import PageActionBar from '../components/PageActionBar';
import ConfirmDialog from '../components/ConfirmDialog';
import StatusBadge from '../components/StatusBadge';
import AccountFormDialog from '../components/AccountFormDialog';
import ChangePasswordForm from '../components/ChangePasswordForm';
import SelfProfileSection from '../components/SelfProfileSection';
import { ROLE_LABELS, ADMIN, userHasRole } from '../constants/roles';
import { useAuth } from '../hooks/useAuth';

function formatLastLogin(iso) {
  if (!iso) return '—';
  const date = new Date(`${String(iso).replace(' ', 'T')}${iso.includes('Z') ? '' : 'Z'}`);
  if (Number.isNaN(date.getTime())) return iso;
  return new Intl.DateTimeFormat('fr-FR', {
    day: '2-digit', month: '2-digit', year: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZone: 'Europe/Paris',
  }).format(date);
}

function statusOf(user) {
  if (!user.isActive) return { status: 'neutral', label: 'Désactivé' };
  if (user.mustChangePassword) return { status: 'warning', label: 'Doit changer son mot de passe' };
  return { status: 'success', label: 'Actif' };
}

function isHardDeletable(user) {
  return user.mustChangePassword && !user.lastLoginAt;
}

function fullName(user) {
  const both = [user.firstName, user.lastName].filter(Boolean).join(' ').trim();
  return both || user.email;
}

export default function UserManagementPage() {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const { user: me, changePassword, refresh: refreshAuth } = useAuth();
  const navigate = useNavigate();
  const isAdmin = userHasRole(me, ADMIN);

  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(isAdmin);  // skip the spinner for non-admins (no list to fetch)
  const [loadError, setLoadError] = useState(null);
  const [snackbar, setSnackbar] = useState(null);
  const [busy, setBusy] = useState(false);
  const [passwordChanged, setPasswordChanged] = useState(false);

  const [formDialog, setFormDialog] = useState({ open: false, mode: 'create', user: null });
  const [formErrors, setFormErrors] = useState({});
  const [resetDialog, setResetDialog] = useState({ open: false, user: null, reactivate: false });
  const [deleteDialog, setDeleteDialog] = useState({ open: false, user: null, hard: false });

  const refresh = useCallback(async () => {
    if (!isAdmin) return;
    setLoading(true);
    setLoadError(null);
    try {
      const data = await api.listUsers();
      setUsers(Array.isArray(data) ? data : (data && data.users) || []);
    } catch (err) {
      setLoadError(err && (err.message || err.error) || 'Impossible de charger les comptes.');
    } finally {
      setLoading(false);
    }
  }, [isAdmin]);

  useEffect(() => { refresh(); }, [refresh]);

  // "Mon mot de passe" — same forced-first-login flow as the old /settings/password page
  // (specs/admin-account-management.md §3.3 rule 15): if the user had mustChangePassword=true at
  // entry, the server destroys the session on success and we redirect to /login.
  const wasMustChange = Boolean(me && me.mustChangePassword);
  const handlePasswordSubmit = useCallback(async (currentPassword, newPassword) => {
    await changePassword(currentPassword, newPassword, { wasMustChange });
    if (wasMustChange) navigate('/login?reason=password-changed', { replace: true });
  }, [changePassword, navigate, wasMustChange]);

  // "Mes informations" — self-service profile editor (specs/admin-account-management.md §6.1).
  // Hits PUT /api/users/me; the server ignores any roles / email key in the payload (privilege
  // guard). On success we refresh the auth state so the sidebar + dialogs pick up the new name.
  const [profileBusy, setProfileBusy] = useState(false);
  const [profileErrors, setProfileErrors] = useState({});
  const handleProfileSubmit = useCallback(async (payload) => {
    setProfileBusy(true);
    setProfileErrors({});
    try {
      await api.updateSelf(payload);
      if (typeof refreshAuth === 'function') await refreshAuth();
      setSnackbar({ severity: 'success', message: 'Vos informations ont été mises à jour.' });
    } catch (err) {
      if (err && err.field) {
        setProfileErrors({ [err.field]: err.detail || err.error });
      } else {
        showError(err, 'Mise à jour impossible.');
      }
    } finally {
      setProfileBusy(false);
    }
  }, []);

  const isSelf = (u) => me && u && Number(me.id) === Number(u.id);

  const showError = (err, fallback = 'Action impossible.') => {
    const detail = err && (err.detail || err.message || err.error) || fallback;
    setSnackbar({ severity: 'error', message: detail });
  };
  const showSuccess = (message) => setSnackbar({ severity: 'success', message });

  // ----- create / edit form -----

  const openCreate = () => {
    setFormErrors({});
    setFormDialog({ open: true, mode: 'create', user: null });
  };
  const openEdit = (user) => {
    setFormErrors({});
    setFormDialog({ open: true, mode: 'edit', user });
  };
  const closeForm = () => setFormDialog({ open: false, mode: 'create', user: null });

  const handleFormSubmit = async (payload) => {
    setBusy(true);
    setFormErrors({});
    try {
      if (formDialog.mode === 'create') {
        await api.createUser(payload);
        showSuccess(`Compte créé. Un mot de passe provisoire a été envoyé à ${payload.email}.`);
      } else {
        await api.updateUser(formDialog.user.id, {
          firstName: payload.firstName,
          lastName: payload.lastName,
          companyName: payload.companyName,
          notes: payload.notes,
          roles: payload.roles,
        });
        showSuccess('Compte mis à jour.');
      }
      closeForm();
      await refresh();
    } catch (err) {
      // Server-side field errors land under their field; everything else lands in the snackbar.
      if (err && err.field) {
        setFormErrors({ [err.field]: err.detail || err.error });
      } else if (err && err.error === 'EMAIL_ALREADY_EXISTS') {
        setFormErrors({ email: 'Cet email est déjà utilisé.' });
      } else {
        showError(err, 'Sauvegarde impossible.');
      }
    } finally {
      setBusy(false);
    }
  };

  // ----- reset password -----

  const openReset = (user) => setResetDialog({ open: true, user, reactivate: false });
  const closeReset = () => setResetDialog({ open: false, user: null, reactivate: false });
  const handleResetConfirm = async () => {
    if (!resetDialog.user) return;
    setBusy(true);
    try {
      await api.resetUserPassword(resetDialog.user.id);
      const verb = resetDialog.reactivate ? 'réactivé' : 'réinitialisé';
      showSuccess(`Compte ${verb}. Un nouveau mot de passe a été envoyé à ${resetDialog.user.email}.`);
      closeReset();
      await refresh();
    } catch (err) {
      showError(err, 'Action impossible.');
    } finally {
      setBusy(false);
    }
  };

  // ----- toggle active -----
  // Deactivating is a clean soft-delete. Reactivating piggybacks on the password reset flow
  // (resetUserPassword sets isActive=1 in the same statement and emails a new temp password), so
  // the reactivated user immediately receives the credentials they need.

  const handleToggleActive = async (user) => {
    if (user.isActive) {
      setBusy(true);
      try {
        await api.deleteUser(user.id);
        showSuccess(`${fullName(user)} désactivé.`);
        await refresh();
      } catch (err) {
        showError(err, 'Désactivation impossible.');
      } finally {
        setBusy(false);
      }
    } else {
      // Open the reset dialog with reactivation copy.
      setResetDialog({ open: true, user, reactivate: true });
    }
  };

  // ----- delete -----

  const openDelete = (user) => setDeleteDialog({ open: true, user, hard: false });
  const closeDelete = () => setDeleteDialog({ open: false, user: null, hard: false });
  const handleDeleteConfirm = async () => {
    const { user, hard } = deleteDialog;
    if (!user) return;
    setBusy(true);
    try {
      await api.deleteUser(user.id, { hard });
      showSuccess(hard ? `${fullName(user)} supprimé définitivement.` : `${fullName(user)} désactivé.`);
      closeDelete();
      await refresh();
    } catch (err) {
      showError(err, 'Suppression impossible.');
    } finally {
      setBusy(false);
    }
  };

  const subtitle = useMemo(() => (
    me && me.email ? (
      <Typography variant="caption" color="text.disabled">{me.email}</Typography>
    ) : null
  ), [me]);

  return (
    <Box>
      <PageActionBar title="Gestion utilisateur" subtitle={subtitle} />

      <Box sx={{ maxWidth: { xs: '100%', md: 1100 }, mx: 'auto', px: { xs: 0, sm: 1 } }}>
        {snackbar && (
          <Alert
            severity={snackbar.severity}
            sx={{ mb: 2 }}
            onClose={() => setSnackbar(null)}
          >
            {snackbar.message}
          </Alert>
        )}

        {/* Section 1 — Mes informations (tous les rôles, profil personnel). */}
        <SelfProfileSection
          initialValues={me}
          fieldErrors={profileErrors}
          busy={profileBusy}
          onSubmit={handleProfileSubmit}
        />

        {/* Section 2 — Mon mot de passe (tous les rôles). */}
        <Card variant="outlined" sx={{ mb: 3 }}>
          <CardContent sx={{ p: { xs: 2, sm: 3 } }}>
            <Stack spacing={2}>
              <Box>
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  Mon mot de passe
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                  Choisissez un nouveau mot de passe d'au moins 10 caractères.
                  {wasMustChange && (
                    <>{' '}Vous serez ensuite redirigé vers la page de connexion pour vous reconnecter avec votre nouveau mot de passe.</>
                  )}
                </Typography>
              </Box>
              {passwordChanged && (
                <Alert severity="success" onClose={() => setPasswordChanged(false)}>
                  Mot de passe mis à jour.
                </Alert>
              )}
              <ChangePasswordForm
                onSubmit={handlePasswordSubmit}
                onSuccess={() => { if (!wasMustChange) setPasswordChanged(true); }}
              />
            </Stack>
          </CardContent>
        </Card>

        {/* Section 3 — Gestion des comptes (admin uniquement). */}
        {isAdmin && (
          <Box>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 1, mb: 1.5, mt: 1 }}>
              <Box>
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  Gestion des comptes
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {users.length} compte{users.length > 1 ? 's' : ''} — créer, modifier, réinitialiser un mot de passe ou supprimer un accès.
                </Typography>
              </Box>
              <Button
                variant="contained"
                size="small"
                startIcon={<PersonAddAlt1Icon />}
                onClick={openCreate}
                disabled={loading}
              >
                Ajouter un compte
              </Button>
            </Box>

            {loadError && (
              <Alert severity="error" sx={{ mb: 2 }}>{loadError}</Alert>
            )}

            {loading && (
              <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
                <CircularProgress />
              </Box>
            )}

            {!loading && users.length === 0 && (
              <Alert severity="info">
                Aucun autre compte. Cliquez sur <strong>Ajouter un compte</strong> pour inviter un
                collaborateur ou un comptable.
              </Alert>
            )}

            {!loading && users.length > 0 && (isMobile
              ? renderMobileCards({ users, me, openEdit, openReset, openDelete, handleToggleActive, busy })
              : renderTable({ users, me, openEdit, openReset, openDelete, handleToggleActive, busy })
            )}
          </Box>
        )}
      </Box>

      <AccountFormDialog
        open={formDialog.open}
        mode={formDialog.mode}
        initialValues={formDialog.user || undefined}
        isSelf={isSelf(formDialog.user)}
        fieldErrors={formErrors}
        busy={busy}
        onClose={closeForm}
        onSubmit={handleFormSubmit}
      />

      <ConfirmDialog
        open={resetDialog.open}
        onClose={closeReset}
        onConfirm={handleResetConfirm}
        title={resetDialog.reactivate ? 'Réactiver le compte' : 'Réinitialiser le mot de passe'}
        message={resetDialog.user ? (resetDialog.reactivate ? (
          <>
            Réactiver le compte de <strong>{fullName(resetDialog.user)}</strong> ? Un nouveau mot de
            passe provisoire lui sera envoyé par email à{' '}
            <strong>{resetDialog.user.email}</strong>.
          </>
        ) : (
          <>
            Réinitialiser le mot de passe de <strong>{fullName(resetDialog.user)}</strong> ?
            Un nouveau mot de passe provisoire lui sera envoyé par email à{' '}
            <strong>{resetDialog.user.email}</strong>.
          </>
        )) : ''}
        confirmLabel="Envoyer"
        confirmColor="primary"
      />

      <ConfirmDialog
        open={deleteDialog.open && !deleteDialog.hard}
        onClose={closeDelete}
        onConfirm={handleDeleteConfirm}
        title="Désactiver le compte"
        message={deleteDialog.user ? (
          <Stack spacing={1}>
            <Box>
              Désactiver le compte de <strong>{fullName(deleteDialog.user)}</strong> ? Il ne pourra
              plus se connecter, mais ses informations sont conservées.
            </Box>
            {isHardDeletable(deleteDialog.user) && (
              <Button
                color="error"
                onClick={() => setDeleteDialog((d) => ({ ...d, hard: true }))}
                size="small"
                sx={{ alignSelf: 'flex-start' }}
              >
                Supprimer définitivement
              </Button>
            )}
          </Stack>
        ) : ''}
        confirmLabel="Désactiver"
        confirmColor="warning"
      />

      <ConfirmDialog
        open={deleteDialog.open && deleteDialog.hard}
        onClose={closeDelete}
        onConfirm={handleDeleteConfirm}
        title="Supprimer définitivement"
        message={deleteDialog.user ? (
          <>
            Supprimer définitivement le compte de <strong>{fullName(deleteDialog.user)}</strong> ?
            Cette action est irréversible.
          </>
        ) : ''}
        confirmLabel="Supprimer"
        confirmColor="error"
      />
    </Box>
  );
}

function renderTable({ users, me, openEdit, openReset, openDelete, handleToggleActive, busy }) {
  return (
    <Card variant="outlined">
      <Box sx={{ overflowX: 'auto' }}>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Nom</TableCell>
              <TableCell>Email</TableCell>
              <TableCell>Rôles</TableCell>
              <TableCell>Société</TableCell>
              <TableCell>Dernière connexion</TableCell>
              <TableCell>Statut</TableCell>
              <TableCell align="right">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {users.map((u) => {
              const isSelf = me && Number(me.id) === Number(u.id);
              const isSelfAdmin = isSelf && (u.roles || []).includes(ADMIN);
              const eligibleHard = isHardDeletable(u);
              const { status, label } = statusOf(u);
              return (
                <TableRow key={u.id} sx={{ opacity: u.isActive ? 1 : 0.6 }}>
                  <TableCell>{fullName(u)}</TableCell>
                  <TableCell>{u.email}</TableCell>
                  <TableCell>
                    <Stack direction="row" spacing={0.5} flexWrap="wrap">
                      {(u.roles || []).map((r) => (
                        <Chip key={r} size="small" label={ROLE_LABELS[r] || r} variant="outlined" />
                      ))}
                    </Stack>
                  </TableCell>
                  <TableCell>{u.companyName || '—'}</TableCell>
                  <TableCell>{formatLastLogin(u.lastLoginAt)}</TableCell>
                  <TableCell><StatusBadge status={status} label={label} /></TableCell>
                  <TableCell align="right">
                    <Stack direction="row" spacing={0.5} justifyContent="flex-end">
                      <Tooltip title="Modifier">
                        <span><IconButton size="small" onClick={() => openEdit(u)} disabled={busy}><EditIcon fontSize="small" /></IconButton></span>
                      </Tooltip>
                      <Tooltip title={isSelf ? 'Utilisez la page Mot de passe pour modifier le vôtre.' : 'Réinitialiser le mot de passe'}>
                        <span><IconButton size="small" onClick={() => openReset(u)} disabled={busy || isSelf}><VpnKeyIcon fontSize="small" /></IconButton></span>
                      </Tooltip>
                      <Tooltip title={u.isActive ? 'Désactiver' : 'Réactiver'}>
                        <span>
                          <IconButton
                            size="small"
                            onClick={() => handleToggleActive(u)}
                            disabled={busy || isSelfAdmin}
                          >
                            {u.isActive ? <ToggleOnIcon fontSize="small" color="success" /> : <ToggleOffIcon fontSize="small" />}
                          </IconButton>
                        </span>
                      </Tooltip>
                      <Tooltip title={
                        isSelf
                          ? 'Vous ne pouvez pas vous supprimer.'
                          : eligibleHard
                            ? 'Désactiver / Supprimer définitivement'
                            : 'Désactiver'
                      }>
                        <span>
                          <IconButton
                            size="small"
                            onClick={() => openDelete(u)}
                            disabled={busy || isSelf}
                            color="error"
                          >
                            <DeleteOutlineIcon fontSize="small" />
                          </IconButton>
                        </span>
                      </Tooltip>
                    </Stack>
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </Box>
    </Card>
  );
}

function renderMobileCards({ users, me, openEdit, openReset, openDelete, handleToggleActive, busy }) {
  return (
    <Stack spacing={1.5}>
      {users.map((u) => {
        const isSelf = me && Number(me.id) === Number(u.id);
        const isSelfAdmin = isSelf && (u.roles || []).includes(ADMIN);
        const { status, label } = statusOf(u);
        return (
          <Card key={u.id} variant="outlined" sx={{ opacity: u.isActive ? 1 : 0.65 }}>
            <CardContent sx={{ p: 2 }}>
              <Stack spacing={1.2}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <Box>
                    <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>{fullName(u)}</Typography>
                    <Typography variant="caption" color="text.secondary">{u.email}</Typography>
                  </Box>
                  <StatusBadge status={status} label={label} />
                </Box>
                <Stack direction="row" spacing={0.5} flexWrap="wrap">
                  {(u.roles || []).map((r) => (
                    <Chip key={r} size="small" label={ROLE_LABELS[r] || r} variant="outlined" />
                  ))}
                </Stack>
                {u.companyName && (
                  <Typography variant="body2"><strong>Société :</strong> {u.companyName}</Typography>
                )}
                <Typography variant="body2"><strong>Dernière connexion :</strong> {formatLastLogin(u.lastLoginAt)}</Typography>
                <Stack direction="row" spacing={0.5} justifyContent="flex-end">
                  <Tooltip title="Modifier">
                    <span><IconButton size="small" onClick={() => openEdit(u)} disabled={busy}><EditIcon /></IconButton></span>
                  </Tooltip>
                  <Tooltip title={isSelf ? 'Utilisez la page Mot de passe pour modifier le vôtre.' : 'Réinitialiser le mot de passe'}>
                    <span><IconButton size="small" onClick={() => openReset(u)} disabled={busy || isSelf}><VpnKeyIcon /></IconButton></span>
                  </Tooltip>
                  <Tooltip title={u.isActive ? 'Désactiver' : 'Réactiver'}>
                    <span>
                      <IconButton size="small" onClick={() => handleToggleActive(u)} disabled={busy || isSelfAdmin}>
                        {u.isActive ? <ToggleOnIcon color="success" /> : <ToggleOffIcon />}
                      </IconButton>
                    </span>
                  </Tooltip>
                  <Tooltip title={isSelf ? 'Vous ne pouvez pas vous supprimer.' : 'Désactiver / supprimer'}>
                    <span>
                      <IconButton size="small" onClick={() => openDelete(u)} disabled={busy || isSelf} color="error">
                        <DeleteOutlineIcon />
                      </IconButton>
                    </span>
                  </Tooltip>
                </Stack>
              </Stack>
            </CardContent>
          </Card>
        );
      })}
    </Stack>
  );
}
